#!/usr/bin/env bash
set -e

rootfsDir="$1"
shift

# specifying --arch below is safe because "$@" can override it and the "latest" one wins :)

(
	set -x
	rinse --directory "$rootfsDir" --arch amd64 "$@"
        umount -l `pwd`/"$rootfsDir"/proc
        umount -l `pwd`/"$rootfsDir"/sys
)

"$(dirname "$BASH_SOURCE")/.febootstrap-minimize" "$rootfsDir"

